name: neo_saver
description: "Uber clone Flutter app - Neo Saver"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  location: ^7.0.1
  geocoding: ^3.0.0
  provider: ^6.1.1
  firebase_core: ^3.13.0     # ✅ Add Firebase Core
  firebase_auth: ^5.5.2     # ✅ Add Firebase Auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/logons.png
    - assets/image/NeoSaver.png
